version: '3.8'

services:
  frontend-dev:
    image: node:18-alpine
    container_name: sifarma-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - sifarma-network

networks:
  sifarma-network:
    driver: bridge